name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when I have to manually copy files..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I would like to drag and drop files from Nautilus directly onto the Aurynk window."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Mockups or Screenshots
      description: |
        If you have a visual idea of how this should look, please drag and drop a screenshot or mockup here.

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.